This is makeindex, version 2.17 [TeX Live 2026/dev] (kpathsea + Thai support).
Scanning style file ./bachelor_thesis_xmacur09.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file bachelor_thesis_xmacur09.acn....done (93 entries accepted, 0 rejected).
Sorting entries....done (636 comparisons).
Generating output file bachelor_thesis_xmacur09.acr....done (84 lines written, 0 warnings).
Output written in bachelor_thesis_xmacur09.acr.
Transcript written in bachelor_thesis_xmacur09.alg.
